# This file was generated by GoReleaser. DO NOT EDIT.
cask "klue" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "914541fa4d19f7bca6f481024a19e8295b654c1839318f540ab75fbdce9a51f0"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a5740a750be0eccc7c6be728e1b871e8978910419d2fbdaff05c5d41c1fc2c9"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00dea4bc34d383421480cea45081f43f9377acc89529dabff39b30efd168d52b"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a5d4aa24d710b35663c789c6dd90ac696ffc0f3fd71ebeb15df44062bb047db"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_linux_arm64.tar.gz"
    end
  end

  name "klue"
  desc "Kubernetes troubleshooting that explains why, not just what."
  homepage "https://github.com/gabor-boros/klue"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klue"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/klue"]
    end
  end

  # No zap stanza required

end
