# This file was generated by GoReleaser. DO NOT EDIT.
cask "klue" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "151b441f6774a7eafdbd62f5196d3fc8c0142e1c61a9c987ca8249e7a911d52b"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c18d273034fb286d9706e37b6bdf5272f79a3f748e6d64b449732bfdfb927e25"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c98ae7d6f8e4fdb6e7beaa88cca083fff72871baccf9b8b20e3d9a9aa69dbf66"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "43ef16d445ffaf4ba8e2fd6cf0da50bccbe798eb4b51a20ac2ae2a889bbb4daa"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_linux_arm64.tar.gz"
    end
  end

  name "klue"
  desc "Kubernetes troubleshooting that explains why, not just what."
  homepage "https://github.com/gabor-boros/klue"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klue"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/klue"]
    end
  end

  # No zap stanza required

end
