# This file was generated by GoReleaser. DO NOT EDIT.
cask "klue" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "70c74fd2babd3bda8da164d516ceeb2aff53c1ae6350cfd2ea73a0b9bb7c5606"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c30dde30f7aa9cf676f6dda24a5ea855d775cf0645df518bf6cefb8e49af2ddf"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a875c92627e3c311bc1d2ea99d032419652a42868a7272bd224e8ce3733273d"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4f5705d91d1512db51ee8a3640620812f77b3b0bacefc8eab30d2fa77188852"
      url "https://github.com/gabor-boros/klue/releases/download/v#{version}/klue_#{version}_linux_arm64.tar.gz"
    end
  end

  name "klue"
  desc "Kubernetes troubleshooting that explains why, not just what."
  homepage "https://github.com/gabor-boros/klue"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klue"

  # No zap stanza required

end
