# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arangom < Formula
  desc "Run ArangoDB migrations with ease."
  homepage "https://github.com/gabor-boros/arangom"
  version "0.3.0"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/arangom/releases/download/v0.3.0/arangom_Darwin_x86_64.tar.gz"
      sha256 "ab05ce276608084a1e677cdb6dd04af26cf0e4a164c5f8c9d110dbe840be4e73"

      def install
        bin.install "arangom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabor-boros/arangom/releases/download/v0.3.0/arangom_Darwin_arm64.tar.gz"
      sha256 "4f5fcaddc54dfc26b192a4a460014a10e6f82a0309c20a4d65ed5afb4cca12a0"

      def install
        bin.install "arangom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/arangom/releases/download/v0.3.0/arangom_Linux_x86_64.tar.gz"
      sha256 "804c7e9c1d6f34c1e102c4c2f9852355c66c7ec108e41752360a41ec94b06afc"

      def install
        bin.install "arangom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabor-boros/arangom/releases/download/v0.3.0/arangom_Linux_arm64.tar.gz"
      sha256 "f06e83ce1b5fe02450df6b89af4fcf9f230f0aa9d82f9ece463678c4cda42863"

      def install
        bin.install "arangom"
      end
    end
  end

  head "https://github.com/gabor-boros/arangom", branch: "main"

  livecheck do
    url "https://github.com/gabor-boros/arangom/releases"
    regex(/^v(\d+(?:\.\d+)+)$/i)
  end
end
