# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arangom < Formula
  desc "Run ArangoDB migrations with ease."
  homepage "https://github.com/gabor-boros/arangom"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabor-boros/arangom/releases/download/v0.2.0/arangom_0.2.0_Darwin_arm64.tar.gz"
      sha256 "1a135bdfb078ce3680a8271ebe34655b7c45ccd7b3e7c17857cd2dc2c2d9def2"

      def install
        bin.install "arangom"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/arangom/releases/download/v0.2.0/arangom_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "736edcfdc9a30ca363cb4c6a983f9dcb7ba149c600d97b4006fb30401d109f3b"

      def install
        bin.install "arangom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabor-boros/arangom/releases/download/v0.2.0/arangom_0.2.0_Linux_arm64.tar.gz"
      sha256 "e5d43ecf99ba406ebd66a085330a4352ede96cedbc412552155eb58f5a1a70c5"

      def install
        bin.install "arangom"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/arangom/releases/download/v0.2.0/arangom_0.2.0_Linux_x86_64.tar.gz"
      sha256 "db4eda385172094060284ade8368a532ae7a1ebad7c38a9d3ce411152f6c1567"

      def install
        bin.install "arangom"
      end
    end
  end

  head "https://github.com/gabor-boros/arangom", branch: "main"

  livecheck do
    url "https://github.com/gabor-boros/arangom/releases"
    regex(/^v(\d+(?:\.\d+)+)$/i)
  end

  depends_on "go" => :build
end
