# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klue < Formula
  desc "Kubernetes troubleshooting that explains why, not just what."
  homepage "https://github.com/gabor-boros/klue"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/gabor-boros/klue/releases/download/v0.1.1/klue_0.1.1_darwin_amd64.tar.gz"
      sha256 "0acb3a14a1b56ab3a836a612bbe1f2caa09d26ce05ea1b6d0af83fa37dc180dc"

      def install
        bin.install "klue"
      end
    end
    on_arm do
      url "https://github.com/gabor-boros/klue/releases/download/v0.1.1/klue_0.1.1_darwin_arm64.tar.gz"
      sha256 "6ca1d3f2b2475cb800b7b730de1c8c74e2bca47403f4cdfbc643234ead52a402"

      def install
        bin.install "klue"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabor-boros/klue/releases/download/v0.1.1/klue_0.1.1_linux_amd64.tar.gz"
        sha256 "1d0b5e46e5be889c995ed56223a454bb2da8ca90d93a56bd6eabfb0abb5beb1b"

        def install
          bin.install "klue"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gabor-boros/klue/releases/download/v0.1.1/klue_0.1.1_linux_arm64.tar.gz"
        sha256 "b802dcf5e32ae9e5fcd3c834711d017fafd26da29d28d719d8f84ccdedb5c651"

        def install
          bin.install "klue"
        end
      end
    end
  end

  head "https://github.com/gabor-boros/klue", branch: "main"

  livecheck do
    url "https://github.com/gabor-boros/klue/releases"
    regex(/^v(\d+(?:\.\d+)+)$/i)
  end
end
