# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minutes < Formula
  desc "Sync worklogs between time trackers, invoicing, and bookkeeping software"
  homepage "https://github.com/gabor-boros/minutes"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabor-boros/minutes/releases/download/v0.3.3/minutes_0.3.3_Darwin_arm64.tar.gz"
      sha256 "3e9b2c3b34f78dd0f8ccb7e3361017b36bde3b3be29f5c49e2344436044f49be"

      def install
        bin.install "minutes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/minutes/releases/download/v0.3.3/minutes_0.3.3_Darwin_x86_64.tar.gz"
      sha256 "dac8d798e29ebea4933bd1ddb83e3d076f413d121de55ddcf7e20b47770c78b6"

      def install
        bin.install "minutes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabor-boros/minutes/releases/download/v0.3.3/minutes_0.3.3_Linux_arm64.tar.gz"
      sha256 "b2d0ea2265206bc348d8c2c65f8a7e3ecab49706a87298ab88938f8964b99b91"

      def install
        bin.install "minutes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/minutes/releases/download/v0.3.3/minutes_0.3.3_Linux_x86_64.tar.gz"
      sha256 "0c9b6077d49876d53138ec687591aff8c07cbe918d3df34c07c923f6640c66a9"

      def install
        bin.install "minutes"
      end
    end
  end

  head "https://github.com/gabor-boros/minutes", branch: "main"

  livecheck do
    url "https://github.com/gabor-boros/minutes/releases"
    regex(/^v(\d+(?:\.\d+)+)$/i)
  end

  depends_on "go" => :build
end
