# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SprintUpdate < Formula
  desc "Generate markdown formatted sprint updates based on the Jira tickets"
  homepage "https://github.com/gabor-boros/sprint-update"
  version "0.1.1"
  license "MIT"
  
  depends_on: "go" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabor-boros/sprint-update/releases/download/v0.1.1/sprint-update_0.1.1_Darwin_arm64.tar.gz"
      sha256 "d6ce02ad03ff3fbbc98caa678d3d9d2715eaed9fb7066d016e045f404461a8eb"

      def install
        bin.install "sprint-update"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/sprint-update/releases/download/v0.1.1/sprint-update_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "5c1eab7a21569f6d7bca664c522aa7c3e11f48b2b466ee54e6edf65e0876cf79"

      def install
        bin.install "sprint-update"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabor-boros/sprint-update/releases/download/v0.1.1/sprint-update_0.1.1_Linux_arm64.tar.gz"
      sha256 "ebca8a12b602d3ceb11d13f7c128d132ac2c8d39b3afdfa585050093bab2d654"

      def install
        bin.install "sprint-update"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/sprint-update/releases/download/v0.1.1/sprint-update_0.1.1_Linux_x86_64.tar.gz"
      sha256 "57d54e111b13bb41d9b9aefeaf573b8574339ea60690a6f6c6bea45ed4fbedd3"

      def install
        bin.install "sprint-update"
      end
    end
  end

  head "https://github.com/gabor-boros/sprint-update", branch: "main"

  livecheck do
    url "https://github.com/gabor-boros/sprint-update/releases"
    regex(/^v(\d+(?:\.\d+)+)$/i)
  end
end
