# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SprintUpdate < Formula
  desc "Generate markdown formatted sprint updates based on the Jira tickets"
  homepage "https://github.com/gabor-boros/sprint-update"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabor-boros/sprint-update/releases/download/v0.1.2/sprint-update_0.1.2_Darwin_arm64.tar.gz"
      sha256 "8fb72c6cfe1f0df3dca488bf029a52e25e4ad7e654bd14b4a55cea89854a0b71"

      def install
        bin.install "sprint-update"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/sprint-update/releases/download/v0.1.2/sprint-update_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "218be143f133a8c24c1cf828ce37057b6c9812f0520415a55c6bc8eb52af6e00"

      def install
        bin.install "sprint-update"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabor-boros/sprint-update/releases/download/v0.1.2/sprint-update_0.1.2_Linux_arm64.tar.gz"
      sha256 "d1dac2ceef898f3cb28555dffbb5342350a434d702bbd6818365ecc3ccb95f02"

      def install
        bin.install "sprint-update"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabor-boros/sprint-update/releases/download/v0.1.2/sprint-update_0.1.2_Linux_x86_64.tar.gz"
      sha256 "6d89da5b467ae06ac2dbe23e5b6e9d71ddb1980ee6e1346e2038e3d8751525f3"

      def install
        bin.install "sprint-update"
      end
    end
  end

  head "https://github.com/gabor-boros/sprint-update", branch: "main"

  livecheck do
    url "https://github.com/gabor-boros/sprint-update/releases"
    regex(/^v(\d+(?:\.\d+)+)$/i)
  end

  depends_on "go" => :build
end
